### ISSUE TITLE
Question on result

### ISSUE THREAD

**Issue by okeeffed** [naquiuddin/postgraphile-nextjs-starter#2]
Random question, but did this repo itself manage to get things working? I've cloned a version and done my own from scratch, but it looks like Graphiql has no results from the Nextjs apps but has a result when using the Postgraphile CLI tool (which has me a little bewildered).

**Comment by naquiuddin** [comment]
I don't remember what exactly happen, but I remember this didn't workout on Vercel server at that time. I would now recommend you either use https://planetscale.com/ or https://supabase.com/ with https://www.prisma.io/. Majorly because it gives you nice Migration Management.

**Comment by okeeffed** [comment]
No worries! I can't remember what I did either in the end 😂  I'll close!
